/**
 * @file ui/items/ui_settings_item.c
 * @brief Reusable settings menu item implementation.
 */

#include "ui_settings_item.h"

#include "ui_icons.h"
#include "ui_theme.h"

#ifndef UI_SETTINGS_ITEM_ICON_FONT
#define UI_SETTINGS_ITEM_ICON_FONT (&lv_font_montserrat_18)
#endif

/**
 * @brief Create an LVGL built-in symbol/text icon.
 *
 * This is used for icons that exist in the normal LVGL font, such as
 * LV_SYMBOL_WIFI.
 */
static void create_text_icon(lv_obj_t *icon_circle, const char *text)
{
    lv_obj_t *icon = lv_label_create(icon_circle);

    lv_label_set_text(icon, text != NULL ? text : "");
    lv_obj_set_style_text_font(icon, UI_SETTINGS_ITEM_ICON_FONT, 0);
    lv_obj_set_style_text_color(icon, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_center(icon);
}

/**
 * @brief Create the custom sun icon from the generated icon font.
 *
 * UI_SYMBOL_SUN is mapped to U+E001 and must be rendered with the
 * lookai_symbols font generated by LVGL font converter.
 */
static void create_sun_icon(lv_obj_t *icon_circle)
{
    lv_obj_t *icon = lv_label_create(icon_circle);

    lv_label_set_text(icon, UI_SYMBOL_SUN);
    lv_obj_set_style_text_font(icon, &lookai_symbols, 0);
    lv_obj_set_style_text_color(icon, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_center(icon);
}

lv_obj_t *ui_settings_item_create(
    lv_obj_t *parent,
    const ui_settings_item_icon_t *icon_config,
    const char *title,
    lv_event_cb_t cb,
    void *user_data
)
{
    uint32_t icon_color = icon_config != NULL ? icon_config->color : UI_COLOR_SECONDARY;

    /*
     * Settings items are intentionally invisible rows. The row itself is still
     * clickable, but there is no card background. Separators are owned by the
     * screen that lays out the menu so lines appear between items.
     */
    lv_obj_t *item = lv_obj_create(parent);

    lv_obj_set_size(item, UI_THEME_BUTTON_WIDTH, UI_THEME_SETTINGS_ITEM_HEIGHT);
    lv_obj_set_style_bg_opa(item, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(item, 0, 0);
    lv_obj_set_style_radius(item, 0, 0);
    lv_obj_set_style_pad_left(item, 4, 0);
    lv_obj_set_style_pad_right(item, 4, 0);
    lv_obj_set_style_pad_top(item, 10, 0);
    lv_obj_set_style_pad_bottom(item, 10, 0);
    lv_obj_set_style_pad_gap(item, 14, 0);
    lv_obj_set_scrollbar_mode(item, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(item, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_flex_flow(item, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(item, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(item, LV_OBJ_FLAG_CLICKABLE);

    if (cb != NULL) {
        lv_obj_add_event_cb(item, cb, LV_EVENT_CLICKED, user_data);
    }

    lv_obj_t *icon_circle = lv_obj_create(item);
    lv_obj_set_size(icon_circle, 52, 52);
    lv_obj_set_style_radius(icon_circle, 26, 0);
    lv_obj_set_style_bg_color(icon_circle, lv_color_hex(icon_color), 0);
    lv_obj_set_style_bg_opa(icon_circle, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(icon_circle, 0, 0);
    lv_obj_set_style_pad_all(icon_circle, 0, 0);
    lv_obj_set_scrollbar_mode(icon_circle, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(icon_circle, LV_OBJ_FLAG_SCROLLABLE);

    if (icon_config != NULL && icon_config->type == UI_SETTINGS_ITEM_ICON_SUN) {
        create_sun_icon(icon_circle);
    } else if (icon_config != NULL && icon_config->type == UI_SETTINGS_ITEM_ICON_WIFI) {
        create_text_icon(icon_circle, LV_SYMBOL_WIFI);
    } else if (icon_config != NULL && icon_config->type == UI_SETTINGS_ITEM_ICON_TEXT) {
        create_text_icon(icon_circle, icon_config->text);
    }

    lv_obj_t *label = lv_label_create(item);
    lv_label_set_text(label, title != NULL ? title : "");
    lv_obj_set_width(label, UI_THEME_BUTTON_WIDTH - 92);
    lv_label_set_long_mode(label, LV_LABEL_LONG_SCROLL);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_LEFT, 0);

    return item;
}
