/**
 * @file ui/items/ui_settings_item.c
 * @brief Reusable settings menu item implementation.
 */

#include "ui_settings_item.h"

#include "ui_icons.h"
#include "ui_theme.h"

#ifndef UI_SETTINGS_ITEM_ICON_FONT
#define UI_SETTINGS_ITEM_ICON_FONT (&lv_font_montserrat_18)
#endif

#ifndef UI_SETTINGS_ITEM_TITLE_FONT
#define UI_SETTINGS_ITEM_TITLE_FONT (&lv_font_montserrat_18)
#endif

/**
 * @brief Create an LVGL built-in symbol/text icon.
 *
 * This is used for icons that exist in the normal LVGL font, such as
 * LV_SYMBOL_WIFI.
 */
static void create_text_icon(lv_obj_t *icon_circle, const char *text)
{
    lv_obj_t *icon = lv_label_create(icon_circle);

    lv_label_set_text_static(icon, text != NULL ? text : "");
    lv_obj_set_style_text_font(icon, UI_SETTINGS_ITEM_ICON_FONT, 0);
    lv_obj_set_style_text_color(icon, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_center(icon);
}

/**
 * @brief Create the custom sun icon from the generated icon font.
 *
 * UI_SYMBOL_SUN is mapped to U+E001 and must be rendered with the
 * lookai_symbols font generated by LVGL font converter.
 */
static void create_sun_icon(lv_obj_t *icon_circle)
{
    lv_obj_t *icon = lv_label_create(icon_circle);

    lv_label_set_text_static(icon, UI_SYMBOL_SUN);
    lv_obj_set_style_text_font(icon, &lookai_symbols, 0);
    lv_obj_set_style_text_color(icon, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_center(icon);
}

lv_obj_t *ui_settings_item_create(
    lv_obj_t *parent,
    const ui_settings_item_icon_t *icon_config,
    const char *title,
    lv_event_cb_t cb,
    void *user_data
)
{
    uint32_t icon_color = icon_config != NULL ? icon_config->color : UI_COLOR_SECONDARY;

    lv_obj_t *item = lv_obj_create(parent);

    lv_obj_set_size(item, UI_THEME_BUTTON_WIDTH, UI_THEME_SETTINGS_ITEM_HEIGHT);
    lv_obj_set_style_bg_color(item, lv_color_hex(UI_COLOR_CARD), 0);
    lv_obj_set_style_bg_color(item, lv_color_hex(UI_COLOR_CARD_PRESSED), LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(item, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(item, lv_color_hex(UI_COLOR_BORDER_SOFT), 0);
    lv_obj_set_style_border_color(item, lv_color_hex(icon_color), LV_STATE_PRESSED);
    lv_obj_set_style_border_width(item, 1, 0);
    lv_obj_set_style_radius(item, 22, 0);
    lv_obj_set_style_pad_all(item, 0, 0);
    lv_obj_set_style_shadow_width(item, 0, 0);
    lv_obj_set_scrollbar_mode(item, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(item, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(item, LV_OBJ_FLAG_CLICKABLE);

    if (cb != NULL) {
        lv_obj_add_event_cb(item, cb, LV_EVENT_CLICKED, user_data);
    }

    lv_obj_t *accent = lv_obj_create(item);
    lv_obj_set_size(accent, 4, 34);
    lv_obj_align(accent, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_style_radius(accent, UI_THEME_PILL_RADIUS, 0);
    lv_obj_set_style_bg_color(accent, lv_color_hex(icon_color), 0);
    lv_obj_set_style_bg_opa(accent, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(accent, 0, 0);
    lv_obj_set_style_pad_all(accent, 0, 0);
    lv_obj_clear_flag(accent, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *icon_circle = lv_obj_create(item);
    lv_obj_set_size(icon_circle, 48, 48);
    lv_obj_align(icon_circle, LV_ALIGN_LEFT_MID, 14, 0);
    lv_obj_set_style_radius(icon_circle, 24, 0);
    lv_obj_set_style_bg_color(icon_circle, lv_color_hex(icon_color), 0);
    lv_obj_set_style_bg_opa(icon_circle, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(icon_circle, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_set_style_border_width(icon_circle, 0, 0);
    lv_obj_set_style_pad_all(icon_circle, 0, 0);
    lv_obj_set_scrollbar_mode(icon_circle, LV_SCROLLBAR_MODE_OFF);
    lv_obj_clear_flag(icon_circle, LV_OBJ_FLAG_SCROLLABLE);

    if (icon_config != NULL && icon_config->type == UI_SETTINGS_ITEM_ICON_SUN) {
        create_sun_icon(icon_circle);
    } else if (icon_config != NULL && icon_config->type == UI_SETTINGS_ITEM_ICON_WIFI) {
        create_text_icon(icon_circle, LV_SYMBOL_WIFI);
    } else if (icon_config != NULL && icon_config->type == UI_SETTINGS_ITEM_ICON_TEXT) {
        create_text_icon(icon_circle, icon_config->text);
    }

    lv_obj_t *label = lv_label_create(item);
    lv_label_set_text_static(label, title != NULL ? title : "");
    lv_obj_set_width(label, UI_THEME_BUTTON_WIDTH - 112);
    lv_label_set_long_mode(label, LV_LABEL_LONG_CLIP);
    lv_obj_set_style_text_font(label, UI_SETTINGS_ITEM_TITLE_FONT, 0);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_COLOR_TEXT), 0);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_LEFT, 0);
    lv_obj_align(label, LV_ALIGN_LEFT_MID, 74, -1);

    lv_obj_t *chevron = lv_label_create(item);
    lv_label_set_text_static(chevron, LV_SYMBOL_RIGHT);
    lv_obj_set_style_text_font(chevron, UI_SETTINGS_ITEM_ICON_FONT, 0);
    lv_obj_set_style_text_color(chevron, lv_color_hex(UI_COLOR_DIM), 0);
    lv_obj_align(chevron, LV_ALIGN_RIGHT_MID, -16, 0);

    return item;
}
