idf_component_register(
    SRCS
        "main.c"
        "ui_status.c"
        "wifi_ap.c"
        "captive_portal.c"
        "dns_server.c"
        "wifi_storage.c"
        "menu_controller.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        esp_http_server
        lwip
)
